name: Deploy Release
on:
  push:
    branches: master

jobs:
  build:
		name: Build 
    runs-on: ubuntu-latest
    steps:
			- name: Checkout Repo
      	uses: actions/checkout@master
      - name: Setup NodeJS
        uses: actions/setup-node@v2.1.0
      - name: Install dependencies
        run: npm install
      - name: Build production
        run: npm run build
	deploy:
		name: Deploy
		needs: build
		runs-on: ubuntu-latest
		steps:
			- name: Checkout Repo
				uses: actions/checkout@master
			- name: Move build to Firebase Hosting
				run: cp -r build/. firebase/public/
			- name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
